# Generated by Django 5.0.4 on 2024-06-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20240625_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
