# Generated by Django 5.0.4 on 2024-06-27 21:51

from django.db import migrations


def set_updated_price(apps, schema_editor):

    MULTYPLIER = 120

    smartphone = apps.get_model('main_app', 'SmartPhone')

    phones = smartphone.objects.all()

    for phone in phones:
        phone.price = len(phone.brand) * MULTYPLIER

    smartphone.objects.bulk_update(phones, ['price'])


def set_updated_category(apps, schema_editor):

    smartphone = apps.get_model('main_app', 'SmartPhone')

    phones = smartphone.objects.all()

    for phone in phones:
        if phone.price < 750:
            phone.category = 'Cheap'

        else:
            phone.category = 'Expencive'

    smartphone.objects.bulk_update(phones, ['category'])


def set_price_and_category(apps, schema_editor):
    set_updated_price(apps, schema_editor)
    set_updated_category(apps, schema_editor)


def set_reversed_price_and_category(apps, schema_editor):

    smartphone = apps.get_model('main_app', 'SmartPhone')

    phones = smartphone.objects.all()

    for phone in phones:
        phone.price = smartphone._meta.get_field('price').default
        phone.category = smartphone._meta.get_field('category').default

    smartphone.objects.bulk_update(phones, ['price', 'category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, set_reversed_price_and_category)
    ]
